"""Episode construction for the inventory simulation (Tier-2 demand model).

Builds :class:`~adaptive_scm.simulation.environment.EpisodeData` in which the
forecast the policy sees is kept distinct from the ground-truth demand:

* **Evaluation** -- the forecast is the frozen forecaster's *actual* prediction
  for the test window; the ground truth is the realized M5 sales. The forecast
  can therefore be wrong, and the policy pays for that error (D-9.7).
* **Training** -- because cheap rolling forecasts over arbitrary historical
  windows are not available, the forecast is a *synthetic* one: the truth plus
  per-day Gaussian error scaled to the forecaster's RMSE, so the agent learns to
  act on forecasts of that forecaster's realistic quality.

Realized demand is generated by the environment from the truth via
forecaster-independent lognormal noise, so replications differ while every
forecaster faces the same world.
"""

from __future__ import annotations

import numpy as np

from adaptive_scm.simulation.environment import FORECAST_WINDOW, EpisodeData
from adaptive_scm.utils.logging import get_logger

_LOG = get_logger(__name__)


def _pad_forecast(values: np.ndarray, window: int) -> np.ndarray:
    """Extend a forecast by ``window`` days, repeating the last value.

    The environment exposes a ``window``-day look-ahead, so the final episode
    days need forecast values past the horizon. Repeating the last point is a
    neutral extrapolation used only for that trailing look-ahead.

    Args:
        values: Forecast values over the episode.
        window: Number of trailing days to append.

    Returns:
        Forecast extended by ``window`` days.
    """
    if window <= 0:
        return values
    return np.concatenate([values, np.full(window, values[-1], dtype=float)])


def build_eval_episode(
    prediction: np.ndarray,
    realized_sales: np.ndarray,
    day_of_week: np.ndarray,
    historical_rmse: float,
    episode_length: int,
    window: int = FORECAST_WINDOW,
) -> EpisodeData:
    """Build the evaluation episode from a real forecast and the realized truth.

    The forecast the policy sees is the forecaster's actual ``prediction`` (padded
    for the look-ahead); the ground-truth ``demand_base`` is the realized sales.
    Forecast error (prediction vs truth) and forecast uncertainty (RMSE) both
    flow into the decision, which is the point of the Tier-2 model.

    Args:
        prediction: Forecaster point prediction for the window, length
            >= ``episode_length``.
        realized_sales: Realized sales (ground truth) for the window, length
            >= ``episode_length``.
        day_of_week: Day-of-week integers, length >= ``episode_length``.
        historical_rmse: Forecaster validation RMSE (forecast uncertainty).
        episode_length: Episode length in days.
        window: Forecast look-ahead length.

    Returns:
        An :class:`EpisodeData` for evaluation.

    Raises:
        ValueError: If ``prediction`` or ``realized_sales`` is too short.
    """
    if len(prediction) < episode_length or len(realized_sales) < episode_length:
        raise ValueError(f"prediction and realized_sales must cover {episode_length} days")
    pred = np.asarray(prediction[:episode_length], dtype=float)
    forecast_mean = _pad_forecast(pred, window)
    forecast_std = np.full(episode_length + window, float(historical_rmse), dtype=float)
    return EpisodeData(
        forecast_mean=forecast_mean,
        forecast_std=forecast_std,
        day_of_week=np.asarray(day_of_week[:episode_length]),
        demand=None,
        demand_base=np.asarray(realized_sales[:episode_length], dtype=float),
        events=np.zeros(episode_length + window, dtype=np.int8),
    )


def make_training_episode_factory(
    sales: np.ndarray,
    day_of_week: np.ndarray,
    historical_rmse: float,
    episode_length: int,
    window: int = FORECAST_WINDOW,
):
    """Return a factory drawing randomized training episodes with synthetic forecasts.

    Each call samples a random start index and slices a window of the series as
    the ground truth. The forecast the agent sees is that truth plus per-day
    Gaussian error of scale ``historical_rmse`` -- a stand-in for the forecaster's
    real prediction with the right error magnitude (D-9.7) -- so the policy
    learns to act on forecasts of that forecaster's quality. Demand itself is
    left unset and generated stochastically by the env from the truth.

    Args:
        sales: Full training-period sales (ground truth).
        day_of_week: Day-of-week integers aligned to ``sales``.
        historical_rmse: Forecaster validation RMSE (forecast-error scale).
        episode_length: Episode length in days.
        window: Forecast look-ahead length.

    Returns:
        A callable ``(rng) -> EpisodeData``.

    Raises:
        ValueError: If the series is too short for one episode plus the window.
    """
    need = episode_length + window
    if len(sales) < need:
        raise ValueError(f"series ({len(sales)}) shorter than episode+window ({need})")
    max_start = len(sales) - need

    def factory(rng: np.random.Generator) -> EpisodeData:
        start = int(rng.integers(0, max_start + 1))
        truth = np.asarray(sales[start : start + episode_length], dtype=float)
        error = rng.normal(0.0, historical_rmse, episode_length)
        synthetic_forecast = np.clip(truth + error, 0.0, None)
        return EpisodeData(
            forecast_mean=_pad_forecast(synthetic_forecast, window),
            forecast_std=np.full(episode_length + window, float(historical_rmse), dtype=float),
            day_of_week=np.asarray(day_of_week[start : start + episode_length]),
            demand=None,
            demand_base=truth,
            events=np.zeros(episode_length + window, dtype=np.int8),
        )

    return factory
