"""Unit tests for Tier-2 episode construction.

Verifies that the evaluation builder keeps the forecaster's prediction (what the
policy sees) separate from the realized truth (what demand is generated from),
pads the forecast for the look-ahead, and that the training factory produces
randomized windows with synthetic forecasts of the right error scale.
"""

from __future__ import annotations

import numpy as np
import pytest

from adaptive_scm.simulation import build_eval_episode, make_training_episode_factory
from adaptive_scm.simulation.environment import FORECAST_WINDOW

_N = 28
_W = FORECAST_WINDOW


class TestBuildEvalEpisode:
    def test_forecast_is_prediction_truth_is_realized(self):
        prediction = np.full(_N, 7.0)
        realized = np.full(_N, 20.0)
        dow = np.arange(_N) % 7
        ep = build_eval_episode(prediction, realized, dow, historical_rmse=3.0, episode_length=_N)
        # forecast the policy sees == prediction (padded); truth == realized.
        assert ep.forecast_mean[0] == pytest.approx(7.0)
        assert ep.demand_base[0] == pytest.approx(20.0)
        assert ep.demand is None  # generated by the env

    def test_forecast_padded_to_episode_plus_window(self):
        prediction = np.arange(_N, dtype=float)
        ep = build_eval_episode(prediction, np.full(_N, 5.0), np.arange(_N) % 7, 2.0, _N)
        assert len(ep.forecast_mean) == _N + _W
        # padding repeats the last predicted value.
        assert ep.forecast_mean[_N] == pytest.approx(prediction[-1])
        assert ep.forecast_mean[-1] == pytest.approx(prediction[-1])

    def test_std_is_rmse(self):
        ep = build_eval_episode(np.full(_N, 5.0), np.full(_N, 5.0), np.arange(_N) % 7, 4.0, _N)
        assert np.all(ep.forecast_std == 4.0)

    def test_rejects_short_inputs(self):
        with pytest.raises(ValueError, match="cover"):
            build_eval_episode(np.full(10, 5.0), np.full(10, 5.0), np.arange(10) % 7, 2.0, _N)


class TestTrainingFactory:
    def test_randomized_windows_differ(self):
        sales = np.arange(400, dtype=float)
        factory = make_training_episode_factory(sales, np.arange(400) % 7, 2.0, 100)
        a = factory(np.random.default_rng(1))
        b = factory(np.random.default_rng(2))
        # Different start indices -> different truth windows.
        assert not np.array_equal(a.demand_base, b.demand_base)

    def test_synthetic_forecast_tracks_truth_with_error(self):
        sales = np.full(400, 10.0)
        factory = make_training_episode_factory(
            sales, np.arange(400) % 7, historical_rmse=2.0, episode_length=100
        )
        ep = factory(np.random.default_rng(0))
        # Synthetic forecast is truth + N(0, rmse): centered near truth, not equal.
        assert ep.demand_base[0] == pytest.approx(10.0)
        assert abs(ep.forecast_mean[:100].mean() - 10.0) < 1.0  # close to truth on average
        assert not np.allclose(ep.forecast_mean[:100], 10.0)  # but has error

    def test_zero_rmse_gives_perfect_training_forecast(self):
        sales = np.full(400, 10.0)
        factory = make_training_episode_factory(sales, np.arange(400) % 7, 0.0, 100)
        ep = factory(np.random.default_rng(0))
        assert np.allclose(ep.forecast_mean[:100], 10.0)

    def test_rejects_short_series(self):
        with pytest.raises(ValueError, match="shorter"):
            make_training_episode_factory(np.arange(50, dtype=float), np.arange(50) % 7, 2.0, 100)
